### ISSUE TITLE
Feature Request: Contribute app development - use Access token instead of ClientId/Secret?

### ISSUE THREAD

**Issue by RonnyWinkler** [tibber/com.tibber.athom#102]
### The feature request

Hello Tibber team,
if I try to run the app locally, I need an ClientId/Secret for oAuth. So far the default behaviour.
In Tibber developer area I can create a privat access token to access "my" data. Is it possible to set this token in env.json to get API access just for development?

I thought about an app widget to show current price and price chart on the new Homey dashboards and would like to try to extend the app. For this scenario, an access token would be enough to run teh app locally I think. But I haven't seen this is used in the app.

Thanks for further information about possibilities of contributing - if it's possible and/or disired :-)
Kind regards
Ronny

**Comment by toini** [comment]
Hi! The (static) personal access token you can retrieve from from developer.tibber.com cannot be automatically rotated and thus not a good practice to use or support for implementing integrations we deploy to other users. We'd rather want people to always integrate with OAuth2. 

However, we can certainly come up with a way you can overcome this in order to contribute! One way could be to just grant you a client id+secret. Another, perhaps simpler, could be for you to override the OAuth2 mechanism locally and just pass your personal access key from a file as the token?

**Comment by RonnyWinkler** [comment]
Hi Toni,
thanks for your fast response!
I adjusted the app code to use the access tokes (set as ENV var). I tried to get a dynamic solution that this tokes is used if provided and oAuth is skipped. Currently I had to remove the first pait screen but I try to get a general solution for such test scenarios.

So far I'm able to run the app locally and I alreday found the access from home device to api instance to read hourly prices.

My main goal is to get a chart on the Homey dasboard. But thinking about I wonder if a simple URL could be provided by Tibber.
If it would be possible to call an URL (with postcode as parameter) that returns an HTML view with only the chart (and perhaps current price and/or min/max) like shown on the homepage, we can add the price chart to the dashboadr using the HTML tile. The page provided by the URL would be shown inside a IFRAME (similar to HomeAssistans Webpage element for HA Dashboards).

Then there is no need to extend the app.

Example from tibber.com:
![grafik](https://github.com/user-attachments/assets/dd1ac774-0ab4-48a5-a875-9ff34e8b8089)

A chart like this without the content around would be very helpful.
![grafik](https://github.com/user-attachments/assets/d2aaebd4-2ede-4717-9895-cc77d436bd6e)

**Comment by toini** [comment]
That could certainly work. The web page is maintained by a different team so there is a risk it could break when they change it so solution encapsulated within this repo would be preferred. I've posted this feature request internally!

**Comment by RonnyWinkler** [comment]
A short update...

- I found a good way to use the access token dynamically by adding it to env.json. I uses a new pair view "loading" as first view where the app checks the existence of an access token to switch over to device list or oAuth.
- I added realtime events to home an pulse device to send instant updates.
- I added a widget where you can select your home and/or pulse (if you have more than one meter).

Current widget example:
![grafik](https://github.com/user-attachments/assets/dfc4c292-c143-44a1-9c15-cd948ded3a6d)

A chart is the next step.

**Comment by RonnyWinkler** [comment]
I created pull request #105 
https://github.com/tibber/com.tibber.athom/pull/105
