### ISSUE TITLE
Bug: Stoped receiving consumption at 13:00 today

### ISSUE THREAD

**Issue by antonhagg** [tibber/com.tibber.athom#103]
### Homey model

Homey (2016 -2019)

### Power adapter

Yes

### The bug

At 13:00 today i stoped receive consumption data. I can still see consumption in the Tibber iphone app. Has there been any changes to the API that breaks the Homey app?

### How frequently does this happen?

Once

### Tibber Premium

no

**Comment by Oddybear** [comment]
I have the same problem
OK in Homey until 13:06 then no update, in Tibbers app it works OK

**Comment by FredStang** [comment]
Same problem here.

**Comment by antonhagg** [comment]
Seems there have been done major issue with Tibber Today. https://status.tibber.com/incidents/13wgycsjmzhr
Seems to be fixed now.
