### ISSUE TITLE
Current price is one of today's lowest/highest [x] prices

### ISSUE THREAD

**Issue by paalrune** [tibber/com.tibber.athom#24]
Når jeg bruker denne Conditions så bruker den X Timer i døgnet. Altså ikke styrt etter pris.
For eksempel:
Hjem
Price changed
Og...
Hjem
Current price is one of today's lowest 6 prices

Denne trigges 00-07.
Når det gjelder høyest  trigges denne 19-00
Dette gjelder både version 1.5.5 og 1.5.8
---
When I use this Conditions it uses X Hours a day. So not controlled by price.
For example:
Home
Price changed
And...
Home
Current price is one of today's lowest 6 prices

This is triggered 00-07.
When it comes to the highest, this is triggered 19-00
This applies to both version 1.5.5 and 1.5.8

**Comment by leiferik** [comment]
Same here, highest price is constantly triggered...

**Comment by gautenk** [comment]
Same here. To me it looks like the trigger is inverted - the lowest [x] tag triggers when the price is high and vice versa.

**Comment by CRidge** [comment]
Just noticed the same. I'm trying to turn certain power consuming devices off for the most expensive three hours of the day. Instead the devices turn off during the three cheapest hours 😔

**Comment by KvennaMekaniske** [comment]
Jeg har også lurt på dette, får det ikke til å funke. Tror også at det er noe rart med price level. Nå er det en av de høyeste prisene i dag (grafen i tibber er ikke grønn), men price level i homey-appen er CHEAP. Dette er i 1.5.10

**Comment by jstaro** [comment]
Thanks for raising this issue. We'll look into it.

**Comment by pteigen** [comment]
I have made changes to an already active PR that fixes these issues:
https://github.com/tibbercom/com.tibber.athom/pull/26

**Comment by paalrune** [comment]
> Thanks for raising this issue. We'll look into it.

will there be a fix this week? I hope so :-)
