### ISSUE TITLE
HighestPrice and LowestPrice

### ISSUE THREAD

**Issue by runely** [tibber/com.tibber.athom#29]
Would be nice to have global tokens for highest price and lowest price today.

**Comment by lovethyresson** [comment]
Hey, thanks for the input!
Can you describe why and how it would be useful for you?

**Comment by runely** [comment]
When I get up in the morning, I could get my sonos speaker to read up todays prices.

This way I would know what I could do and shouldn't do today energy wise

**Comment by runely** [comment]
It can also be a pointer for those who use price indication on whether something should be activated today or not.

There are probably a lot more use cases here :)
