### ISSUE TITLE
Add electricity network costs to all price logics

### ISSUE THREAD

**Issue by marlov74** [tibber/com.tibber.athom#30]
The same way we can enable taxes to all prices I would like to include variable part of the largest network companies types of agreements.
For example: I’ve a Vattenfall T4 agreement.
The distribution cost is 0.18SEK offpeak and 0.60SEK peak.

**Comment by lovethyresson** [comment]
Hi,

Agreed this would be useful. Today we only have this for certain grid companies, but will expose it as soon as we are in a good position too.
