### ISSUE TITLE
Not able to add device "Home"

### ISSUE THREAD

**Issue by sharpblur** [tibber/com.tibber.athom#48]
My "Home" is not showing when trying to add device.
This is after login/pass. 

![image](https://user-images.githubusercontent.com/114179545/191811620-4a4edd76-d067-4622-9884-42f85573156e.png)
![image](https://user-images.githubusercontent.com/114179545/191811737-a632af2d-8384-43f5-8f95-fc32fb96f31f.png)
![image](https://user-images.githubusercontent.com/114179545/191811864-933beb47-ddeb-491f-a4cb-6478b8cc81fc.png)
![image](https://user-images.githubusercontent.com/114179545/191811979-94e2a39b-f266-45f6-8dc0-397cb70e54c8.png)
---Loginscreen passed OK---
![image](https://user-images.githubusercontent.com/114179545/191812232-f1b6c32c-28ba-407e-b419-186bcfbf9ca5.png)
![image](https://user-images.githubusercontent.com/114179545/191812316-16fbe630-98d6-44da-b1e4-7c5fafff2694.png)

**Comment by toini** [comment]
Network request failed indicates (typically intermittent) networking error. Does your Homey have a stable network connection?
