### ISSUE TITLE
Fail when reinstall the Home device 

### ISSUE THREAD

**Issue by MagnusPer** [tibber/com.tibber.athom#49]
I had a problem where the Price level not had been updated for 20h. I asked in the Homey community if any other had the same problem and the answer where NO. So the failure was on my side! 

I reinstalled the Tibber App and when adding the Home device I'm not able to add it back its says "You can now close the window". I'm not redirected to the Tiber wall for login with my credentials to get access.

Help needed!

**Comment by Rallmo** [comment]
I had exactly the same issue and did the same thing. 

I’m redirected to Tibber and able to log in but still it says no new units found when trying to add the home again in Homey.

**Comment by Rallmo** [comment]
Started working now for me!

**Comment by MagnusPer** [comment]
Still failing for me but now I at least are redirected and are able to log in but as you wrote "_it says no new units found when trying to add the home again in Homey_"

**Comment by jstaro** [comment]
Do you have subscriptions starting in the future? We have fixed a bug elsewhere that had, for a long time, allowed pairing homes in the Homey app before your subscription's start date. We are going to discuss in the team the ramifications of fixing this bug and what the original intent here actually was.

@Rallmo I'd wager a guess that your subscription started today?

**Comment by MagnusPer** [comment]
@jstaro - my subscription starts 18th of October. So It might be the problem, how ever I managed last week to create to login an to get the “home” device. The problem started after the uninstallation!

**Comment by Rallmo** [comment]
@jstaro almost, it started yesterday! :)

Thanks for the response!

**Comment by jstaro** [comment]
@MagnusPer The bug in our API that previously allowed the pairing of the home was fixed sometime last week, so you probably managed to squeak through the first time, but no longer can re-pair. Sorry for the inconvenience and please stay tuned.

**Comment by Giorgisme** [comment]
I have the same problem

**Comment by jstaro** [comment]
We've decided to change this, but it will need a new release of the Homey app, and we have some other fixes/minor features we also want to sneak in, so it won't be released immediately.

Meanwhile, rest assured you should be able to pair your home on the day of your official subscription start.

**Comment by MagnusPer** [comment]
@jstaro - Great you maintain and update this app with new features. I’m closing in on the date my subscription starts and by then this problem is for me behind! But for new cubers not having a subscription it’s of importance to get it fixed.

**Comment by The-element** [comment]
https://github.com/tibber/tibber.bugs/issues/1389 <- duplicate.

**Comment by jstaro** [comment]
This should now work for subscriptions starting in the future.

**Comment by MagnusPer** [comment]
Great 👍 But hard for me to verify since I have the subscription active now!
