### ISSUE TITLE
Unable to recover after Tibber Pulse 504 Gateway Timeout

### ISSUE THREAD

**Issue by iver56** [tibber/com.tibber.athom#54]
I found my Homey Tibber app in this error state earlier today, and it seemed unable to recover from this state by itself. At the same time my Tibber Pulse was up and running (live with real-time updates) in the Tibber Android app.

![bilde](https://user-images.githubusercontent.com/1470603/198882657-4ba9b78b-4581-42a4-9852-bdcf74e7497a.png)

Restarting the Tibber app in Homey (from the settings menu) helped. But I don't want to monitor the Tibber app and restart it manually. Ideally it should be able to help itself out of the bad state after the backend is up and running again.

**Comment by jstaro** [comment]
Which version of the app are you using, 1.8.1 or 1.8.2?

**Comment by iver56** [comment]
It says here

> Tibber has been automatically updated to version 1.8.1
> 5 days ago

So I'm using 1.8.1 at the moment. There does not seem to be a way for me to update it manually, but the switch "Update Automatically" is enabled

**Comment by iver56** [comment]
My Homey has upgraded to 1.8.2, I'll reopen if this happens again.
