### ISSUE TITLE
Tibber suddenly stopped working

### ISSUE THREAD

**Issue by antonhagg** [tibber/com.tibber.athom#62]
Tibber suddenly stopped working today. I get an error that the ID is not found. This is the second time in just a few month that it stops working. The consequense is that Homey didnt know my consumption and didnt turn of the heating and I now get a higher cost on my nettleie because I consumed over 5kwh in one hour. :(

edit: reading some other closed issues I found that restarting the Tibber app in Homey (from the settings menu) helped. But I don't want to monitor the Tibber app and restart it manually. Ideally it should be able to help itself out of the bad state.

Error log: 71e69582-eb9f-4478-a657-ca08c6773761

![B2C64276-4FFE-415E-AEAD-4BC68D2AA2A3](https://user-images.githubusercontent.com/16721156/208325259-f7c36afb-cb83-4aba-aee4-1dfda3df7dd3.jpeg)

**Comment by antonhagg** [comment]
reading some other closed issues I found that restarting the Tibber app in Homey (from the settings menu) helped. But I don't want to monitor the Tibber app and restart it manually. Ideally it should be able to help itself out of the bad state after the backend is up and running again.

**Comment by jstaro** [comment]
One of our upstream services had a partial outage and this, combined with some bad error handling in the Tibber API (to prevent the Homey app from restarting over and over in case of a lost Pulse) caused the Homey app to mark this device as unavailable, which should only really happen if the Pulse or Watty is permanently unavailable, not just transiently, which it was in this case.

We pushed out a new version of the Homey app yesterday to basically force-restart it for everyone. The error handling should have been improved now so hopefully this shouldn't happen again.

Sorry for the inconvenience.
