### ISSUE TITLE
Trigger not working

### ISSUE THREAD

**Issue by larskristianhaga** [tibber/com.tibber.athom#73]
None of the Tibber triggers works in the Homey App `V1.9.7`.

Example of a simple flow that is never triggered, but should trigger once every hour.
![Screenshot 2023-03-10 at 15 33 08](https://user-images.githubusercontent.com/13958865/224350337-4aeac986-47d8-4685-a9b1-1aad52167a5b.png)

Diagnostic code: `6fc89194-2e11-4206-98e3-65463210e016`.

**Comment by jstaro** [comment]
Your subscription ended in December, and you cannot get prices from our API in that case. Currently our Homey app does not automatically disable your home device in Homey when the subscription ends.

The app does use Nord Pool for fallback prices but only for Pulse/Watty.
