### ISSUE TITLE
And: Current price is one of the 4 lowest prices between 15:00 and 21:00

### ISSUE THREAD

**Issue by havardbe** [tibber/com.tibber.athom#75]
Hello, as my title says I'm using a "Current price is one of the 4 lowest prices between 15:00 and 21:00", this argument returns false even if it is the 2nd lowest price throughout the entire day (and also the lowest between 15:00 and 21:00).

This 'false' was returned at 15:30.

The next hour 16:12 this flow card returned 'true', but the 'current price' was higher from 16:00 - 17:00 than it was from 15:00 - 16:00. It was the 2nd lowest between 15:00 - 21:00 and the 4th lowest throughout the day

diagnostic ID: 4f7b5e45-b6ee-42d0-afa3-d58574586d94

**Comment by emilialu** [comment]
Hello,  

Looking at your diagnostic report it shows that there has been some issues with comparing prices at the time, which is why the return has been `false`.

Is this `And` card not working still an ongoing issue for you?

**Comment by havardbe** [comment]
I noticed the issue the day before as well, but I am have afterwards
replaced the Tibber app with another app with the same functionality.
